name: Build and Dockerize Spring Boot App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - +ä~ä*ÜÖÜ*~~
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install JDK 17
        run: chmod +x ./src/main/java/com/example/helloworld/shellsScrpts/installJava.sh

      - name: Build Docker image
        run: docker build -t springboot-docker-app .

      - name: Run Docker image
        run: docker run -p 8080:8080 springboot-docker-app

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        run: chmod +x src/main/java/com/example/helloworld/shellsScrpts/checkResponseCode.sh
          with:
            time: '5m'