name: Build and Dockerize Spring Boot App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Run Maven clean and package
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t springboot-docker-app .

      # Step 5: Run Docker image
      - name: Run Docker image
        run: docker run -p 8080:8080 springboot-docker-app

      # Step 6: Check status
      - name: Check status
        run: src/main/java/com/example/helloworld/shellsScrpts/checkResponseCode.sh
